// <auto-generated />
namespace LoanProgram.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _1More : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1More));
        
        string IMigrationMetadata.Id
        {
            get { return "202011192132032_1More"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
